
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: R-Packages_development

test:
  <<: *default
  database: R-Packages_test
  
production:
  <<: *default
  database: R-Packages_production
  username: R-Packages
  password: <%= ENV['R-PACKAGES_DATABASE_PASSWORD'] %>
